export const projects = [
  {
    id: 1,
    slug: "punggol-hdb-renovation",
    title: "HDB 4-Room - 664A Punggol Drive",
    category: "Residential",
    location: "Punggol Drive",
    duration: "8 weeks",
    designer: "Strata Design Team",
    style: "Modern • Contemporary",
    mainImage: "/images/projects/punggol-hdb/cover.jpg",
    gallery: [
      "/images/projects/punggol-hdb/cover.jpg",
      "/images/projects/punggol-hdb/living-area.jpg",
      "/images/projects/punggol-hdb/main-living.jpg",
      "/images/projects/punggol-hdb/bedroom.jpg",
      "/images/projects/punggol-hdb/study-room-1.jpg",
      "/images/projects/punggol-hdb/study-room-2.jpg",
      "/images/projects/punggol-hdb/study-room-3.jpg",
      "/images/projects/punggol-hdb/study-room-4.jpg",
      "/images/projects/punggol-hdb/living-area-2.jpg",
      "/images/projects/punggol-hdb/study-corner.jpg",
      "/images/projects/punggol-hdb/entertainment-wall.jpg",
      "/images/projects/punggol-hdb/kitchen-cabinets.jpg",
      "/images/projects/punggol-hdb/kitchen-cooking.jpg",
      "/images/projects/punggol-hdb/living-ceiling.jpg",
      "/images/projects/punggol-hdb/entertainment-unit.jpg",
    ],
    description:
      "Complete 4-room HDB renovation featuring modern design, custom carpentry, and optimized living spaces.",
    fullDescription:
      "This comprehensive 4-room HDB renovation at Punggol Drive showcases contemporary design excellence with custom-built furniture and thoughtful space planning. The project features a stunning open-concept living and dining area with feature ceiling lighting, a fully integrated modern kitchen with island, and a beautifully designed study room with built-in storage and desk solutions. Premium finishes, strategic lighting design, and clean lines throughout create a sophisticated yet comfortable family home.",
  },
  {
    id: 2,
    slug: "marine-terrace-hdb-renovation",
    title: "HDB 4-Room - Marine Terrace",
    category: "Residential",
    location: "Marine Terrace",
    duration: "10 weeks",
    designer: "Strata Design Team",
    style: "Luxury • Contemporary",
    mainImage: "/images/projects/marine-terrace-hdb/completed-living.jpg",
    gallery: [
      "/images/projects/marine-terrace-hdb/completed-living.jpg",
      "/images/projects/marine-terrace-hdb/luxury-bathroom.jpg",
      "/images/projects/marine-terrace-hdb/living-entertainment.jpg",
      "/images/projects/marine-terrace-hdb/bathroom-vanity.jpg",
      "/images/projects/marine-terrace-hdb/completed-bathroom.jpg",
      "/images/projects/marine-terrace-hdb/empty-room.jpg",
      "/images/projects/marine-terrace-hdb/renovation-progress.jpg",
      "/images/projects/marine-terrace-hdb/bathroom-construction.jpg",
      "/images/projects/marine-terrace-hdb/bathroom-progress.jpg",
      "/images/projects/marine-terrace-hdb/tile-installation.jpg",
    ],
    description:
      "Luxury 4-room HDB renovation featuring premium black marble floors, geometric tile patterns, and sophisticated finishes.",
    fullDescription:
      "This exceptional 4-room HDB renovation at Marine Terrace represents the pinnacle of luxury residential design. The project showcases premium black marble flooring throughout, sophisticated geometric tile patterns in the bathrooms, and high-end built-in entertainment systems. The transformation includes custom carpentry work, modern lighting solutions, and meticulous attention to detail in every space. The bathrooms feature stunning chevron-patterned tiles, contemporary fixtures, and spa-like finishes that create a resort-style living experience.",
  },
  {
    id: 3,
    slug: "orchid-park-condo-yishun",
    title: "Orchid Park Condo - Yishun",
    category: "Residential",
    location: "Yishun",
    duration: "12 weeks",
    designer: "Strata Design Team",
    style: "Luxury • Contemporary",
    mainImage: "/images/projects/orchid-park-condo/cover.jpg",
    gallery: [
      "/images/projects/orchid-park-condo/cover.jpg",
      "/images/projects/orchid-park-condo/entertainment-unit.jpg",
      "/images/projects/orchid-park-condo/modern-kitchen.jpg",
      "/images/projects/orchid-park-condo/living-room-blue.jpg",
      "/images/projects/orchid-park-condo/coral-bedroom.jpg",
      "/images/projects/orchid-park-condo/luxury-bathroom-1.jpg",
      "/images/projects/orchid-park-condo/main-living.jpg",
      "/images/projects/orchid-park-condo/bathroom-vanity.jpg",
      "/images/projects/orchid-park-condo/living-area.jpg",
      "/images/projects/orchid-park-condo/master-bedroom.jpg",
    ],
    description:
      "Luxury condominium renovation featuring sophisticated color schemes, premium marble finishes, and custom built-in solutions.",
    fullDescription:
      "This stunning condominium renovation at Orchid Park showcases exceptional design sophistication with bold color choices and premium materials. The project features a striking entertainment unit with integrated LED lighting, a modern kitchen with yellow glass backsplash, and luxurious bathrooms with dark marble finishes. Each room demonstrates thoughtful color coordination - from the serene blue living spaces to the vibrant coral bedroom and elegant teal master suite. The renovation combines contemporary aesthetics with functional design, creating a truly distinctive living environment that reflects modern luxury living.",
  },
  {
    id: 4,
    slug: "citylink-skincare-shop",
    title: "Luxury Skincare Shop at CityLink - City Hall",
    category: "Commercial",
    location: "CityLink Mall, City Hall",
    duration: "6 weeks",
    designer: "Strata Design Team",
    style: "Luxury • Commercial",
    mainImage: "/images/projects/citylink-skincare-shop/cover.jpg",
    gallery: [
      "/images/projects/citylink-skincare-shop/cover.jpg",
      "/images/projects/citylink-skincare-shop/reception-area.jpg",
      "/images/projects/citylink-skincare-shop/consultation-area.jpg",
      "/images/projects/citylink-skincare-shop/treatment-room.jpg",
      "/images/projects/citylink-skincare-shop/facial-pod-room.jpg",
      "/images/projects/citylink-skincare-shop/corridor-cabinetry.jpg",
      "/images/projects/citylink-skincare-shop/corridor-marble.jpg",
      "/images/projects/citylink-skincare-shop/treatment-corridor.jpg",
      "/images/projects/citylink-skincare-shop/reception-angle.jpg",
      "/images/projects/citylink-skincare-shop/construction-phase.jpg",
    ],
    description:
      "High-end skincare and beauty shop featuring luxury marble finishes, professional treatment rooms, and sophisticated commercial design.",
    fullDescription:
      "This premium skincare shop renovation at CityLink Mall showcases exceptional commercial design with luxury marble columns, glass partitions, and sophisticated lighting throughout. The TRUE HARMONY brand space features a stunning curved reception area, multiple private treatment rooms equipped with professional skincare equipment, and elegant consultation spaces. The design incorporates premium materials including marble accent walls, modern wood cabinetry, and commercial-grade flooring to create a spa-like atmosphere that reflects the brand's commitment to luxury skincare services. Professional treatment rooms are equipped with specialized facial equipment and designed for optimal client comfort and privacy.",
  },
  {
    id: 5,
    slug: "novena-restaurant-bar",
    title: "Restaurant Bar at Novena Square - Novena",
    category: "Commercial",
    location: "Novena Square, Novena",
    duration: "8 weeks",
    designer: "Strata Design Team",
    style: "Industrial • Contemporary",
    mainImage: "/images/projects/novena-restaurant-bar/cover.jpg",
    gallery: [
      "/images/projects/novena-restaurant-bar/cover.jpg",
      "/images/projects/novena-restaurant-bar/dining-area.jpg",
      "/images/projects/novena-restaurant-bar/bar-interior.jpg",
      "/images/projects/novena-restaurant-bar/full-bar-view.jpg",
      "/images/projects/novena-restaurant-bar/bar-setup.jpg",
      "/images/projects/novena-restaurant-bar/dining-bar-area.jpg",
      "/images/projects/novena-restaurant-bar/seating-area.jpg",
      "/images/projects/novena-restaurant-bar/exterior-view.jpg",
      "/images/projects/novena-restaurant-bar/construction-flooring.jpg",
      "/images/projects/novena-restaurant-bar/renovation-phase.jpg",
    ],
    description:
      "Modern restaurant and sports bar featuring industrial design, extensive bar facilities, and contemporary dining spaces.",
    fullDescription:
      "This sophisticated restaurant and bar renovation at Novena Square showcases industrial contemporary design with exposed ceiling elements, brick accent walls, and polished concrete flooring. The project features Harry's Bar + Dining with an extensive liquor collection, professional bar setup, and comfortable dining areas with teal upholstered seating. The space combines sports bar functionality with upscale dining aesthetics, featuring multiple TV screens, distinctive pendant lighting, and a comprehensive beverage program. The industrial design elements are balanced with warm wood accents and modern furnishings to create an inviting atmosphere for both casual drinks and dining experiences.",
  },
  {
    id: 6,
    slug: "mandarin-gardens-condo-marine-parade",
    title: "Mandarin Gardens Condo - Marine Parade",
    category: "Residential",
    location: "Marine Parade",
    duration: "10 weeks",
    designer: "Strata Design Team",
    style: "Modern • Contemporary",
    mainImage: "/images/projects/mandarin-gardens-condo/cover.jpg",
    gallery: [
      "/images/projects/mandarin-gardens-condo/cover.jpg",
      "/images/projects/mandarin-gardens-condo/bedroom-teal.jpg",
      "/images/projects/mandarin-gardens-condo/living-curved-ceiling.jpg",
      "/images/projects/mandarin-gardens-condo/bedroom-blue.jpg",
      "/images/projects/mandarin-gardens-condo/bedroom-blue-alt.jpg",
      "/images/projects/mandarin-gardens-condo/wardrobe-storage.jpg",
      "/images/projects/mandarin-gardens-condo/living-dining.jpg",
      "/images/projects/mandarin-gardens-condo/bathroom-modern.jpg",
      "/images/projects/mandarin-gardens-condo/kitchen.jpg",
      "/images/projects/mandarin-gardens-condo/bathroom-shower.jpg",
    ],
    description:
      "Sophisticated condominium renovation featuring modern design, custom built-in storage, and elegant color schemes throughout.",
    fullDescription:
      "This elegant condominium renovation at Mandarin Gardens showcases contemporary design excellence with sophisticated color palettes and premium finishes. The project features stunning teal and blue accent walls, extensive built-in wardrobes with wood-grain finishes, and beautiful parquet flooring throughout. The design includes curved ceiling details with modern pendant lighting, spacious living and dining areas with warm accent walls, and luxurious bathrooms with contemporary fixtures and feature stone walls. Custom carpentry solutions maximize storage while maintaining clean, modern aesthetics. The kitchen features wood-grain cabinets with black countertops and modern appliances, creating a cohesive design that balances functionality with sophisticated style.",
  },
]
